# Site Settings
title: Pat's Blog | Pat Cody's Personal Blog
email: patcody028@gmail.com
description: 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://patcody.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: pcodes
user_description: Student and developer. 
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: pcodes
twitter_username:  therealpatcody
linkedin_username: pcodes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
